version: "3.9"  # optional since v1.27.0
services:
  service:
    build: .
    volumes:
      - .:/app
      - ./ips.txt:/app/ips.txt
      - ./GeoLite2-City.mmdb:/app/geolite.mmdb
    environment:
      - PING_INTERVAL=30
      - HTTP_ENABLE=true
      - GEOMIND_DATABASE=/app/geolite.mmdb
      - INPUT_FILE=/app/ips.txt
    ports:
      - 8080:8080
